language: java
jdk: openjdk8

script:
  - mvn -B clean package

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  - MAVEN_OPTS=-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

cache:
  directories:
  - $HOME/.m2
